### ISSUE TITLE
请问这个demo是如何解决事务问题的?

### ISSUE THREAD

**Issue by tangxusc** [wangboliang/cqrs-axon-demo#1]
我在代码中看到只是发送event到了mq中,但是并没有解决事务问题
commandBus 发送了 command 后,后面就是异步执行的了,在发送event的过程中如果宕机或者网络中断,那么evnet就存在没有发送成功的可能,这时候业务怎么处理呢?
event我也没看到重发,或者利用持久化的机制来进行存储,以便下次恢复的时候重发.
对于最终一致性我还有一个比较大的疑惑,
例如 我集群中存在 3台服务器,使用event来达到一致性
有一个需要检查余额才能进行的业务,某用户余额现有1000元,第一次调用转出900,发送了转出900的事件,3台服务器其中的两台都已经消费了事件,另外一台消费较慢(服务器配置不好)
现在,用户又点击一次转出900,刚好命中消费较慢的那一台,那么 这台服务器怎么判断该用户是否有足够的钱转出呢? 或者说有什么办法可以解决这样的问题呢?

**Comment by wangboliang** [comment]
非常不好意思。这个demo还没有完善好。cqrs是一种命令查询职责分离模式。整过过程如下：前端发送请求调用后台接口，commandBus发送指令，然后通过@CommandHandler注解监听处理（一个command只能被监听一次，每个command都有一个唯一标识）。在处理函数中new一个聚合根。在聚合根构造函数apply event事件（event通过mongodb做持久化，一个event可以被监听多次，每个event都有一个唯一标识）。在saga类中监听多个event事件，通过全局变量记录状态判断操作回滚。

**Comment by wangboliang** [comment]
你描述的问题，我的理解大概是这个思路：在saga中监听event事件处理扣减余额函数过程如果失败，发送一个新的command回滚操作。
